meta_name: "Tango Bravo"
meta_title: "Tango Bravo *◊* Time Building"
meta_description: "Connecting pilots and aircraft owners for time buiding and passive income"
meta_image: "logo.png" # should exist in `app/assets/images/`
